### ISSUE TITLE
[APIC-168] - Add support for PropertyShape

### ISSUE THREAD

**Issue by jarrodek** [advanced-rest-client/api-view-model-transformer#2]
```yaml
#%RAML 1.0
---
title: SecuritySchemes
version: v1

securitySchemes:
  queryString:
      type: x-Custom
      describedBy:
        queryString:
            type: integer
            required: true

/querystring:
  securedBy: [ queryString ]
  get:
```
The view model for auth method is not generated for this API
